import { execFile, spawnSync } from 'node:child_process';
import { writeFile } from 'node:fs/promises';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { BrowserWindow, dialog, shell } from 'electron';

/**
 * Export an action plan as a Markdown file and hand it over to Claude Code.
 *
 * Integration is strictly through PUBLIC, supported mechanisms: we write a
 * plain .md file the user chooses the location of, then launch the documented
 * `claude` CLI in a new terminal with an initial prompt pointing at that file.
 * If the CLI is not installed, we fall back to revealing the file so the user
 * can open it in any Claude surface manually.
 */

export interface PlanExportRequest {
  readonly title: string;
  /** Markdown body (without the top-level title). */
  readonly body: string;
  readonly suggestedName?: string;
  /** Preferred directory (e.g. the analyzed project root). */
  readonly targetDir?: string;
  /** Attempt to launch Claude Code on the exported file. Default true. */
  readonly launch?: boolean;
}

export interface PlanExportResult {
  readonly ok: boolean;
  readonly path?: string;
  readonly launched: boolean;
  readonly message: string;
}

function claudeCliAvailable(): boolean {
  const probe = process.platform === 'win32' ? 'where' : 'which';
  try {
    return spawnSync(probe, ['claude'], { timeout: 3000 }).status === 0;
  } catch {
    return false;
  }
}

function launchClaudeTerminal(planPath: string, cwd: string): boolean {
  const prompt = `Read the file "${planPath}" and carry out the improvements it describes, step by step. Ask before destructive changes.`;
  try {
    if (process.platform === 'win32') {
      // A new cmd window that stays open running the documented Claude Code CLI.
      execFile('cmd.exe', ['/c', 'start', 'Claude Code', 'cmd', '/k', `claude "${prompt}"`], {
        cwd,
        windowsHide: false,
      });
      return true;
    }
    if (process.platform === 'darwin') {
      const script = `tell application "Terminal"
  do script "cd ${cwd.replace(/"/g, '\\"')} && claude \\"${prompt.replace(/"/g, '\\\\\\"')}\\""
  activate
end tell`;
      execFile('osascript', ['-e', script]);
      return true;
    }
    // Linux: try common terminal emulators in order.
    const shellCmd = `cd '${cwd.replace(/'/g, "'\\''")}' && claude '${prompt.replace(/'/g, "'\\''")}'; exec bash`;
    for (const [term, args] of [
      ['x-terminal-emulator', ['-e', `bash -c "${shellCmd}"`]],
      ['gnome-terminal', ['--', 'bash', '-c', shellCmd]],
      ['konsole', ['-e', 'bash', '-c', shellCmd]],
      ['xterm', ['-e', 'bash', '-c', shellCmd]],
    ] as const) {
      if (spawnSync('which', [term], { timeout: 2000 }).status === 0) {
        execFile(term, args as unknown as string[], { cwd });
        return true;
      }
    }
    return false;
  } catch {
    return false;
  }
}

/** Show a save dialog, write the plan, then try to hand it to Claude Code. */
export async function exportPlan(request: PlanExportRequest): Promise<PlanExportResult> {
  const win = BrowserWindow.getFocusedWindow();
  const defaultDir = request.targetDir ?? homedir();
  const res = await dialog.showSaveDialog(win!, {
    title: 'Export plan for Claude Code',
    defaultPath: join(defaultDir, request.suggestedName ?? 'CEM-PLAN.md'),
    filters: [{ name: 'Markdown', extensions: ['md'] }],
  });
  if (res.canceled || !res.filePath) {
    return { ok: false, launched: false, message: 'Export cancelled.' };
  }

  const markdown = `# ${request.title}\n\n> Generated by Claude Environment Manager (CEM). Review each item before applying.\n\n${request.body}\n`;
  await writeFile(res.filePath, markdown, 'utf8');

  if (request.launch !== false && claudeCliAvailable()) {
    const launched = launchClaudeTerminal(res.filePath, dirname(res.filePath));
    if (launched) {
      return {
        ok: true,
        path: res.filePath,
        launched: true,
        message: 'Plan exported — Claude Code was opened in a new terminal with the plan loaded.',
      };
    }
  }

  shell.showItemInFolder(res.filePath);
  return {
    ok: true,
    path: res.filePath,
    launched: false,
    message:
      'Plan exported. Claude Code CLI was not launched automatically — open the file in Claude Code (e.g. run: claude "read CEM-PLAN.md and apply it").',
  };
}
